"""user table updated to fix load_user and add email to ticket talbe

Revision ID: 8445d319d616
Revises: b875c06d844d
Create Date: 2020-04-12 14:35:48.617964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8445d319d616'
down_revision = 'b875c06d844d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('description', sa.String(length=1000), nullable=True))
    op.add_column('ticket', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('ticket', sa.Column('firstname', sa.String(length=64), nullable=True))
    op.add_column('ticket', sa.Column('lastname', sa.String(length=64), nullable=True))
    op.add_column('ticket', sa.Column('location', sa.String(length=200), nullable=True))
    op.add_column('ticket', sa.Column('phone_number', sa.String(length=10), nullable=True))
    op.add_column('ticket', sa.Column('status', sa.String(length=35), nullable=True))
    op.add_column('ticket', sa.Column('subject', sa.String(length=140), nullable=True))
    op.create_index(op.f('ix_ticket_email'), 'ticket', ['email'], unique=False)
    op.create_index(op.f('ix_ticket_firstname'), 'ticket', ['firstname'], unique=False)
    op.create_index(op.f('ix_ticket_lastname'), 'ticket', ['lastname'], unique=False)
    op.create_index(op.f('ix_ticket_location'), 'ticket', ['location'], unique=False)
    op.create_index(op.f('ix_ticket_phone_number'), 'ticket', ['phone_number'], unique=False)
    op.create_index(op.f('ix_ticket_subject'), 'ticket', ['subject'], unique=False)
    op.drop_column('ticket', 'body')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.drop_index(op.f('ix_ticket_subject'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_phone_number'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_location'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_lastname'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_firstname'), table_name='ticket')
    op.drop_index(op.f('ix_ticket_email'), table_name='ticket')
    op.drop_column('ticket', 'subject')
    op.drop_column('ticket', 'status')
    op.drop_column('ticket', 'phone_number')
    op.drop_column('ticket', 'location')
    op.drop_column('ticket', 'lastname')
    op.drop_column('ticket', 'firstname')
    op.drop_column('ticket', 'email')
    op.drop_column('ticket', 'description')
    # ### end Alembic commands ###
